# docker-compose.yml (simplificado)
version: "3.8"
services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    environment:
      - CLUSTER_NAME=bigdata
    ports:
      - "9870:9870"
    volumes:
      - hadoop_namenode:/hadoop/dfs/name

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    depends_on:
      - namenode
    ports:
      - "9864:9864"

  spark-master:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=master
      - USER=spark
    ports:
      - "8080:8080"
    volumes:
      - ./scripts:/scripts
      - ./bases:/bases

  spark-worker:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - USER=spark
    depends_on:
      - spark-master
    ports:
      - "8081:8081"

volumes:
  hadoop_namenode:
